### ISSUE TITLE
Roxie does not start properly due to insufficient heap space

### ISSUE THREAD

**Issue by oxhead** [vin0110/haas#10]
After an HPCC cluster is initialized, the Roxie service is not ready due to insufficient heap space.  This problem can be reproduced on t2.micro instances.  Need to make sure this issue does not happen on instances with a larger memory size.

**Comment by oxhead** [comment]
### t2.micro
This instance size has too few memory; therefore, it does not have enough memory to run Roxie.  We don't need to handle this case because this depends on how Roxie handles the memory allocation.

### 1-slave cluster
The default numDataCopies in Roxie prevents it from starting.  This issue has been solved by checking parameter values.

**Comment by vin0110** [comment]
Super.
