### ISSUE TITLE
Implement a configuration manager

### ISSUE THREAD

**Issue by oxhead** [vin0110/haas#16]
We use dict to keep the configuration parameters.  However, as the project goes by, it becomes very difficult to manage/track all these parameters, e.g., ctx.obj['region'].  We need a configuration context/manager to keep all these parameters across all commands.

**Comment by vin0110** [comment]
I agree this can (and should) be improve. However, we are limited to what click allows. It "passes context" between commands with the `@click.pass_context` decorator. I believe it only passes the dictionary `ctx.obj`. 

I tried adding an attribute to the context in one command, i.e.,
```python
setattr(ctx, 'debug', somevalue)
```
However, the ctx received by subcommand did not have the debug attr. But if 
```python
ctx.obj['debug'] = somevalue
```
the ctx inherited by the subcommand has debug defined in the obj dictionary.

**Comment by oxhead** [comment]
You are correct.  I couldn't find a way to add arbitrary attributes to **ctx**.
