### ISSUE TITLE
Cannot create stack

### ISSUE THREAD

**Issue by vin0110** [vin0110/haas#29]
The following command failed
```
haas stack create -p 'template_url=https://raw.githubusercontent.com/vin0110/haas/master/templates/haas_cft.json' -p MasterInstanceType=t2.micro -p KeyName=osr -p ClusterSize=2 twonodes2
```

Error message
```
You have requested more instances (6) than your current instance limit of 5 allows for the specified instance type. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit. Launching EC2 instance failed.
```

Events are [here](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn:aws:cloudformation:us-east-1:169987671570:stack%2Ftwonodes2%2F2cb6efd0-7c6f-11e7-8c6a-503acac41efd)

Think it should have created one master and two slaves. But it tried to created 6 EC2 instances.

**Comment by oxhead** [comment]
That's weird.  Let me look into this issue.

**Comment by vin0110** [comment]
I think the problem is the number of ec2 instances is cumulative and there were 2 stacks already consuming some ec2 instances.

I will close this after verified.

**Comment by oxhead** [comment]
We can create stacks as expected.  I closed this issue.
