### ISSUE TITLE
CFT and AMI(s)

### ISSUE THREAD

**Issue by vin0110** [vin0110/haas#3]
**Basic CFT.** Establishes N + "1" cluster.  Parameters for: N (and 1), worker AMI (and master AMI), EBS volumes per worker and for master.

**Basic AMI.** Assuming (for now) that one AMI for both worker and master is sufficient. Each node will be able to determine its role (master or worker). After more is learned, it may make sense to have different AMI for master. The current AMI should be good enough.

**Comment by oxhead** [comment]
The prototype can be found in #7.

**Comment by oxhead** [comment]
Should we close this one since it's merged into the mater branch?
