### ISSUE TITLE
No stack id in stack create output

### ISSUE THREAD

**Issue by vin0110** [vin0110/haas#37]
Stack create prints:
```
StackId:
```

The code is 
```python
        stack_id = response['StackId'] if 'StackId' in response else None
        message("StackId:", str(stack_id))
```

If response never contains StackId (1) why was this code written and (2) it should be removed. If it sometimes does contain id, then message should be conditionally printed.

**Comment by oxhead** [comment]
I believe this one is solved.  Can we close this one?
