### ISSUE TITLE
Resize command

### ISSUE THREAD

**Issue by vin0110** [vin0110/haas#46]
Implement _resize_ command. It has to resize up (eg, from a 10-node cluster to a 20-node cluster) and down.

First, verify that the _restore_ command will "properly" restore to a differently sized cluster. What is "properly"? It only concerns files that where divided into parts. There are two case when the number of parts (P) is different from the number of slave nodes (N).

When P < N, just place the partitions on the first P nodes of the cluster. When N > P, place the partitions by wrapping so that partition P goes on node P (mod N).

Once _restore_ is verified (or corrected) to do the above. We need to implement the _resize_ command to change the "layout" of partitioned files. Partitioning is done via "spraying." It might be that we need to _despray_ and respray each file. The alternative is to use the ECL _distribute_ function. The question is whether that is want we want. Distribute operates on a recordset. It probably does not change the files.

**Comment by oxhead** [comment]
Once dataset is redistributed, we can call **OUTPUT** for writing the changes back to DFS.

**Comment by vin0110** [comment]
@oxhead What is the status of this command?

**Comment by oxhead** [comment]
Still working on that.  I will have a working prototype  either later today or  tomorrow.

**Comment by vin0110** [comment]
Thx
