### ISSUE TITLE
Make AMI a parameter to CFT

### ISSUE THREAD

**Issue by vin0110** [vin0110/haas#49]
AMI is hard-coded in base [cft](https://github.com/vin0110/haas/blob/master/templates/haas_cft.json).

This should be parameterized.

**Comment by vin0110** [comment]
Looks like region is hard coded, too.

**Comment by oxhead** [comment]
Should we prepare a customized AMI or a base AMI with initialization script?

**Comment by vin0110** [comment]
Let's just do custom AMI for now. AMI creation is orthogonal to haas.
