### ISSUE TITLE
Refactor haas actions

### ISSUE THREAD

**Issue by vin0110** [vin0110/haas#54]
There are actions that are executed on the master node to support haas operations. For example, when client executes `haas data save` it creates a process on the master node that does the save. Currently, this code is in haascli but should be in a separate module that is copied to the master node.

For example.
  * The client runs `haas stack save ...`
  * This remotely executes `python /opt/haas/bin/server-side-of-save-command.py ...`

The name of the py module above should be something else.

In addition to refactoring, we need a reliable way to

**Comment by oxhead** [comment]
Please refer to #51 .  There are separated from the haas cli.

In terms of reliability, we should discuss our current implementation.

**Comment by vin0110** [comment]
Note this work was done under #47.
