### ISSUE TITLE
Redo cluster command format

### ISSUE THREAD

**Issue by vin0110** [vin0110/haas#66]
The stack command format for commands needing stack name is:
```
haas stack subcommand <stack_name> [options]
```
whereas the format for cluster is:
```
haas cluster -s <stack_name> subcommand [options]
```

Both are reasonable but there should be one standard format. I prefer the former (ie, the way is it done in stack).

**Comment by vin0110** [comment]
The data subcommands have format similar to cluster. Let's change those commands as well.

**Comment by oxhead** [comment]
@vin0110  which part of the data command you suggest to change?  Currently we have

```
haas data --resource workunit restore mycheckpoint1 mycluster2
```

**Comment by vin0110** [comment]
No other command have options between command class and subcommand. So I suggest
```
haas data subcommand <stackname> <resource> <checkpoint> 
```
But the last two could be in the other order.
